# Numpy

NumPy is a Python library used for working with arrays. 
It also has functions for working in domain of linear algebra, fourier transform, and matrice

In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.a Arrays are very frequently used in data science, where speed and resources are very important. Is a PyNumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.thon library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

***

In [2]:
# The first thing is import NumPy
import numpy as np

In [5]:
## For collaborate with people, you should samain version numpy 
# check the version

print(np.__version__)

1.26.4


In [6]:
# make a numpy array

a = np.array([1,2,3,4,5])

In [7]:
print(a)

[1 2 3 4 5]


In [8]:
print(type(a))

<class 'numpy.ndarray'>


In [9]:
# use a tuple to create a Numpy array

b = np.array(("Class B", "Group 1", "Data Analyst"))

In [10]:
print(b)

['Class B' 'Group 1' 'Data Analyst']


In [11]:
print(type(b))

<class 'numpy.ndarray'>


## Dimension

***

#### Dimension in Arrays

Dimensions are groups of attributes based on columns from tables or views in a data source view. Dimensions exist independent of a cube, can be used in multiple cubes, can be used multiple times in a single cube. A dimension that exists independent of a cube is called a database dimension and an instance of a database dimension within a cube is called a cube dimension.

A dimension in Arrays is one level of array depth (nested arrays).

In [19]:
# 0-D Arrays

import numpy as np

a = np.array(25)
print(a)

25


In [36]:
# 1-D Arrays

import numpy as np

b = np.array([2,4,6,8,10])
print(b)

[ 2  4  6  8 10]


In [39]:
#call the two and three element
print(b[2] + b[3])

14


In [31]:
# create a 2-D array containing two array

c = np.array([[3,5,7], [9,11,13]])
print(c)

[[ 3  5  7]
 [ 9 11 13]]


In [35]:
#make your word
c = np.array([[3,5,7], [9,11,13]])
print('3th element from 2nd row is:', c [1,2])

3th element from 2nd row is: 13


In [24]:
# create a 3-D array with two 2-D arrays, both contain two array

d = np.array([[[3,5,7], [11,13,15]], [[3,5,7], [11,13,15]]])
print(d)

[[[ 3  5  7]
  [11 13 15]]

 [[ 3  5  7]
  [11 13 15]]]


In [26]:
# Check how many dimension the arrays have

a = np.array(25)
b = np.array([2,4,6,8,10])
c = np.array([[3,5,7], [9,11,13]])
d = np.array([[[3,5,7], [11,13,15]], [[3,5,7], [11,13,15]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [3]:
# Make 4-D array
arr = np.array([[[[11,12,13], [14,15,16]], [[1,2,3], [4,5,6]]]])
print(arr[0,0,1,2])

#

16


In [4]:
print(arr.ndim)

4
